function w_gui_test(varargin)
f=figure('MenuBar', 'none', 'ToolBar', 'none', 'Name', 'Test', 'NumberTitle', 'off');
hp = uipanel('Title','','FontSize',12,...
             'BackgroundColor', [0.7, 0.7, 0.7],...
             'Position',[.25 .1 .67 .67]);
c=uicontrol(hp, 'Style', 'pushbutton', 'String', 'test button',...
    'Units', 'normalized', 'Position', [0,0,1,1],...
    'Callback', @w_disp);

function w_disp(h, ent, x)
disp('Button pushed')
